### PR TITLE
[Feat] Make use of the data stored in SharedInformer stores and refactor codebase

### PR DESCRIPTION
**Pull request by sudo-NithishKarthik**
**Description**

This PR makes leverages the data that are in the `Stores` that `SharedInformers` maintain so that a client, such as Meshery Server does not have to ask MeshSync to resync every time it needs to replay the old events to arrive at the current state of the cluster. I have also refactored some parts of the codebase.

**Notes for Reviewers**

- There are some places where I have added TODO statements since they require changes to be done in MeshKit. Those will be addressed in a different PR.

- Error codes are yet to be created for the functionalities that has been introduced in this PR, which would be addressed in a different PR.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Revolyssup — APPROVED** [review]

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Ready to merge?

**Comment by leecalcote** [comment]
An issue needs to be opened on MeshKit to track the TODOs.

**Comment by Revolyssup** [comment]
> Ready to merge?

I think @utkarsh-pro  should review this once

**Comment by leecalcote** [comment]
That would be great. If @utkarsh-pro doesn't respond by Monday, we'll need to move on without him.

**Review by utkarsh-pro — APPROVED** [review]
LGTM

**Pull request merged**
