### PR TITLE
[Enhancement] Use Streaming Lists when available

### PR DESCRIPTION
**Pull request by MUzairS15**
Reverts meshery/meshsync#247

### CODE REVIEW

**Comment by MUzairS15** [comment]
// @KiptoonKipkurui

**Comment by MUzairS15** [comment]
REmove the `do-not-merge` label when ready.

**Comment by leecalcote** [comment]
@KiptoonKipkurui do we need this PR or only #255?

**Comment by KiptoonKipkurui** [comment]
Only the #255 is sufficient

**Pull request closed without merging**
