### PR TITLE
Upgraded to Golang v1.17

### PR DESCRIPTION
**Pull request by MUzairS15**
**Description**

This PR fixes #

**Notes for Reviewers**

* Upgraded to Golang v1.17.
* Fix Makefile error.
**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you. Don’t forget about MeshKit.

**Review by leecalcote — APPROVED** [review]

**Comment by MUzairS15** [comment]
dependabot will do it.

**Comment by MUzairS15** [comment]
https://github.com/meshery/meshsync/pull/113

**Comment by leecalcote** [comment]
> dependabot will do it.

We’ll want to specify the helm cart release name as that upgrade occurs, I think

**Comment by MUzairS15** [comment]
meshkit v0.5.11 added the  `ReleaseName` field which resulted in conflicts, meshkit v0.5.12 added backward compatibility for the same.
So, according to me we are good to go.

**Pull request merged**
