### PR TITLE
 [Enhancement] Use Streaming Lists when available

### LINKED ISSUE #221: [Enhancement] Use Streaming Lists when available
### Current Behavior
MeshSync performs discovery of specific Kubernetes API types using watches and sharedInformers.

### Desired Behavior
Enhance MeshSync to use [Streaming Lists](https://kubernetes.io/docs/reference/using-api/api-concepts/#streaming-lists) when available in the managed Kubernetes cluster.

### Implementation:
1. Verify whether Streaming Lists are available. If so, use them.

### Acceptance Criteria
1. When Streaming Lists are not available, downgrade to current methodology.
1. Confirm that all of the same resource details are retrieved via Streaming Lists as are retrieved using the current methodology. 

### Contributor Resources

The meshery.io website uses Jekyll and GitHub Pages. Site content is found under the [`master` branch](https://github.com/meshery/meshery.io/tree/master).
- See the [Contributing to Meshery.io Website](https://github.com/layer5io/meshery.io#contributing-to-the-mesheryio-website) section of the readme.md and other [contributing instructions](https://docs.meshery.io/project/contributing), too.
- See [Meshery site designs](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI?node-id=110%3A1) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9). 
- Fill-in a [Community Member Form](https://layer5.io/newcomer) and join the [Community Slack](http://slack.meshery.io) for access.

### PR DESCRIPTION
**Pull request by KiptoonKipkurui**
**Description**
This PR Addresses an issue of potential runaway usage of memory due to chucking of reported statuses while watching for Kubernetes resources. Kubernetes 1.27 introduces a WatchList feature still at the alpha stage that allows one to get statuses of objects being watched as a streaming list as opposed to current implementations that uses a list request first before a watch request. This is done by setting sendInitialEvents=true param in a watch request.
This PR fixes #221

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by KiptoonKipkurui** [comment]
Point to note, So this PR is against a branch of meshery where the original PR was made and Reverted to

**Comment by leecalcote** [comment]
@KiptoonKipkurui did you toss in the towel here?

**Comment by KiptoonKipkurui** [comment]
@leecalcote no I hadn't, by my last commit I had resolved the pending issues by then and comments, it was just a matter merging if all was well from the maintainers side

**Pull request closed without merging**
