### PR TITLE
[database] Update KeyValues table with composite key | CU-2nqagta

### PR DESCRIPTION
**Pull request by theBeginner86**
Signed-off-by: Pranav Singh <pranavsingh02@hotmail.com>

**Description**
- **Earlier** 
For KeyValues table we had `unique_id` as primary key. Which leads to duplication of data in the table. This was because `unique_id` is a randomly generated uuid format number that would be different in every scenario and hence was leading to duplicate entries being inserted into the DB. Moreover, rebooting of Meshery server was leading to re-registering of all the labels and thus leading to doubling of label count on each reboot.
eg: For id=`YjM4NWU2YzMtM2RmYi00NTFjLWFmMjYtMWMwZjViYmU4ZjU5LlNlcnZpY2UudjEuZGVmYXVsdC5kZWZhdWx0LW1lc2hlcnktb3BlcmF0b3ItNmQ2MTY1NzM2OC1tZXNoZXJ5` it shows 30 enteries.

Screenshot 2022-08-08 at 6 44 35 PM

- **Now** 
This PR makes `id`, `kind`, `key` and `value` together as a primary key (works as composite key). So, in every scenario, new entries would only be entered into the DB if each of `id`, `kind`, `key` and `value` are different otherwise it would just update that.
eg: In reality for id=`YjM4NWU2YzMtM2RmYi00NTFjLWFmMjYtMWMwZjViYmU4ZjU5LlNlcnZpY2UudjEuZGVmYXVsdC5kZWZhdWx0LW1lc2hlcnktb3BlcmF0b3ItNmQ2MTY1NzM2OC1tZXNoZXJ5`there was just 2 entries, rest all were duplicates.
Screenshot 2022-08-08 at 6 50 32 PM

_`id` represents a resource object_ which is bound to have more than one label. Hence, this PR makes a composite key which keeps in context the `id`, `kind`, `key` and `value` which won't be same in any given scenario.

This PR fixes #

**Notes for Reviewers**
This would likely help in increasing the performance of MeshMap as these labels are traversed through loops in formulating objects for Visualiser.

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by sudo-NithishKarthik** [comment]
what is the difference between `UniqueId` and `id`?

**Comment by sudo-NithishKarthik** [comment]
Usually, we use composite keys for M:M relationship tables. But there is no hard rule as such, as long as we have a proper use case. For us, I guess we can just keep an `identity` primary key and make the rest(`kind`, `key` etc. ) unique. The main reason why I am saying this is that using composite keys will make things unnecessarily complex at the ORM layer.

**Comment by theBeginner86** [comment]
> what is the difference between `UniqueId` and `id`? Is it necessary to have both of them?

No, it isn't. The one which is necessary is `id`.
- `id`: uniquely identifies an object discovered in cluster. Works as foreign key for other tables like: `object`, `resource_spec`, `resource_object_meta`, `resource_status`.
- `unique_id`: randomly generated UUID no. We aren't referring it anywhere.

**Comment by leecalcote** [comment]
bumpity, bump

**Comment by leecalcote** [comment]
@sudo-NithishKarthik @theBeginner86 what do we want to do here?

**Comment by sudo-NithishKarthik** [comment]
@theBeginner86 what do u think?

**Comment by theBeginner86** [comment]
> @theBeginner86 what do u think?

@sudo-NithishKarthik 
I believe that we should go ahead with this PR as it seems to solve a problem, i.e, `redundant values in DB`.
This should definitely improve the performance of MeshMap visualiser.
Eg:
Screenshot 2022-09-22 at 5 43 13 PM

See, I haven't flushed my MeshSync data in a month (I believe 🤔), and we can see the no of key-values (i.e., labels and annotations) have almost reached a million!
But in reality it should be < 500.

**Comment by theBeginner86** [comment]
@sudo-NithishKarthik 

Though, if this implementation might have an overhead as your described in this [comment](https://github.com/meshery/meshsync/pull/144#issuecomment-1209302350), then should we go with some other approach?
I believe that, if we just make `id` as primary key as describe by you in above comments, then it would still not solve the problem as then we won't be able to store more than one label/annotation for a single resource, since an `id` represent a resource.

Though I also thought of decomposing the DB further using some mapping table but that might require more thought and extra changes into other repos/projects that currently refers this local Meshery DB.

Or do you have some other approach with which we can solve this issue?

**Comment by leecalcote** [comment]
@sudo-NithishKarthik review needed.

**Comment by sudo-NithishKarthik** [comment]
@theBeginner86 , you are right. This PR solves a problem which is critical to the Visualizer. Let us merge this PR and then discuss the other issue separately since it does not have much of a functional impact as of now.

**Comment by leecalcote** [comment]
Syncing with `master`....

**Review by leecalcote — APPROVED** [review]

**Pull request merged**
